name: Renew Katabump

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 */3 * *'  # 每三天运行一次
  push:
    paths:
      - 'renew.py'

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright and browser
        run: |
          pip install playwright
          playwright install chromium

      - name: Unzip captcha solver extension
        run: |
          mkdir -p extensions/captcha-solver
          unzip captcha.crx -d extensions/captcha-solver || ture
          ls -R extensions/captcha-solver

      - name: Run renew script
        env:
          KATABUMP_EMAIL: ${{ secrets.KATABUMP_EMAIL }}
          KATABUMP_PASSWORD: ${{ secrets.KATABUMP_PASSWORD }}
          KATABUMP_SERVER_ID: ${{ secrets.KATABUMP_SERVER_ID }}
        run: python renew.py

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: katabump_error_screenshot
          path: |
            *.png
